version: 2
updates:
  - package-ecosystem: yarn
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
    target-branch: 'main'
    open-pull-requests-limit: 10
    rebase-strategy: 'disabled'
