services:
  - type: web
    name: acceptance-test-example-webapp
    env: static
    plan: free
    repo: https://github.com/neil-armstrong-instil/react-acceptance-tests-example
    branch: main
    rootDir: webapp
    buildCommand: yarn install && yarn compile
    staticPublishPath: ./build
