services:
  - type: web
    name: acceptance-test-example-webapp
    env: static
    repo: https://github.com/neil-armstrong-instil/react-acceptance-tests-example
    branch: main
    rootDir: webapp
    buildCommand: yarn install && yarn compile
    staticPublishPath: ./webapp/build
  - type: web
    name: acceptance-test-example-api
    env: node
    plan: free
    repo: https://github.com/neil-armstrong-instil/react-acceptance-tests-example
    branch: main
    rootDir: api
    buildCommand: yarn install && yarn compile
    startCommand: yarn start:prod
    healthCheckPath: /
