name: Run on every commit

on: [ push ]

jobs:
  commitChecks:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/reusable-actions/setup-project

#      - name: Run checks
#        uses: ./.github/reusable-actions/check-project

      # TODO: Delete below
      - name: Install xserver
        run: sudo apt-get update && sudo apt-get install xorg openbox

      - name: Install playwright dependencies
        run: yarn workspace acceptance-test-example-acceptance-tests setup

      - name: Sync webapp
        run: yarn workspace acceptance-test-example-webapp compile && yarn sync-webapp

      - name: Package application
        run: yarn package

      - name: Try to run electron package directly
        run: electron/dist/linux-unpacked/acceptance-test-example-electron

      - name: Run acceptance tests
        run: yarn workspace acceptance-test-example-acceptance-tests acceptance-tests

  acceptanceTests:
    needs: commitChecks
    if: github.ref == 'refs/heads/main'
    concurrency: "1"
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/reusable-actions/setup-project

      - name: Install playwright dependencies
        run: yarn workspace acceptance-test-example-acceptance-tests setup

      - name: Sync webapp
        run: yarn workspace acceptance-test-example-webapp compile && yarn sync-webapp

      - name: Package application
        run: yarn package

      - name: Check deployments
        env:
          RENDER_APIKEY: ${{secrets.RENDER_APIKEY}}
        run: yarn checkDeployments

      - name: Run acceptance tests
        run: yarn workspace acceptance-test-example-acceptance-tests acceptance-tests

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: acceptance-tests/screenshots
