name: Run on every commit

on: [ push ]

jobs:
  commitChecks:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/reusable-actions/setup-project

      - name: Run checks
        uses: ./.github/reusable-actions/check-project

  acceptanceTests:
    needs: commitChecks
    if: github.ref == 'refs/heads/main'
    concurrency: "1"
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/reusable-actions/setup-project

      - name: Install playwright dependencies
        run: yarn workspace acceptance-test-example-acceptance-tests setup

      - name: Sync webapp
        run: yarn workspace acceptance-test-example-webapp compile && yarn sync-webapp

      - name: Package application
        run: yarn package

      - name: Check Webapp deployment
        uses: neil-armstrong-instil/render-deployment-checker@v1
        env:
          RENDER_APIKEY: ${{secrets.RENDER_APIKEY}}
        with:
          serviceId: "srv-cdqc0larrk09t4b2bd50"
          deploymentName: "Webapp"

      - name: Check API deployment
        uses: neil-armstrong-instil/render-deployment-checker@v1
        env:
          RENDER_APIKEY: ${{secrets.RENDER_APIKEY}}
        with:
          serviceId: "srv-cdqc0larrk09t4b2bd40"
          deploymentName: "API"

      - name: Install x11 gui
        run: |
          sudo apt-get update && sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &

      - name: Run acceptance tests with x11 gui
        run: xvfb-run --auto-servernum yarn workspace acceptance-test-example-acceptance-tests acceptance-tests

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: acceptance-tests/screenshots
